### ISSUE TITLE
Cant login w/ credentials

### ISSUE THREAD

**Issue by Christian1998** [Tustin/cod-php#2]
Hey Tustin, awesome work, but i think something has changed...
Tried ur "full example" and got just
`Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://profile.callofduty.com/cod/mapp/login` resulted in a `500 Internal Server Error` response: {"requestURL":"https://profile.callofduty.com/cod/mapp/login","errorMessage":null,"exceptionClass":"NullPointerException (truncated...) in C:\xampp\htdocs\cod\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\xampp\htdocs\cod\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\cod\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 C:\xampp\htdocs\cod\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 C:\xampp\htdocs\cod\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}( in C:\xampp\htdocs\cod\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113`

I would thank u for any help :)

**Comment by Tustin** [comment]
API might have changed a bit since I last worked on this. 500 error indicates that there is something wrong with their API login.

**Comment by Christian1998** [comment]
> API might have changed a bit since I last worked on this. 500 error indicates that there is something wrong with their API login.

Yea i think so too because their app isnt working. Which program are u using to get all api parameters and so on? Currently tried it w/ Fiddler but cant get it working... Would appreciate ur help :)

**Comment by EthanC** [comment]
The API is inaccessible to third parties at this time: https://charlieintel.com/call-of-duty-api-changes-kill-third-party-statistic-tracking-websites-and-services/52576/

**Comment by Tustin** [comment]
@Christian1998 I used Fiddler as well; didn't have any problems with it. There could be a chance that they added certificate pinning but I doubt it. Alternatively, you can use their normal website (https://my.callofduty.com). It has basically the same stuff as the app.
